robot_urdf:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Controller 1
  j_support_right_controller: # change the name
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: j_support_right # Name of the joint.  
    pid : {p: 250.0, i: 2.00, d: 3.0} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
  # Controller 2
  j_support_left_controller: # change the name
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: j_support_left # Name of the joint.  
    pid : {p: 250.0, i: 2.0, d: 3.0} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
  # Controller 3
  j_rear_left_wheel_controller: # change the name
    type: velocity_controllers/JointVelocityController # Type of controller. 
    joint: j_rear_left_wheel # Name of the joint.  
  # Controller 4
  j_rear_right_wheel_controller: # change the name
    type: velocity_controllers/JointVelocityController # Type of controller. 
    joint: j_rear_right_wheel # Name of the joint.  